version: '3'

services:
  percona:
    image: percona:5.6.40
    container_name: percona
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: somedb
    ports:
      - 127.0.0.1:3306:3306

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    ports:
      - 127.0.0.1:6379:6379
